name: bukuing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.1.0

  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  file_picker: ^5.3.1
  cloud_firestore: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets : 
  - assets/images/