// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz7qAegqxpTDZMWFg7oHc7JaevhdV79n0',
    appId: '1:661451733735:web:db1c48c493db6975690042',
    messagingSenderId: '661451733735',
    projectId: 'bukuing-application',
    authDomain: 'bukuing-application.firebaseapp.com',
    storageBucket: 'bukuing-application.appspot.com',
    measurementId: 'G-091L31ML2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvaW7ZfijdF2_NMXmUAa86_hmg9th0fQI',
    appId: '1:661451733735:android:4a33e0891f09e94b690042',
    messagingSenderId: '661451733735',
    projectId: 'bukuing-application',
    storageBucket: 'bukuing-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVb2q4f7Jv6kXKfZdfWC_XfxS6DbzbIj8',
    appId: '1:661451733735:ios:c029010c67e151eb690042',
    messagingSenderId: '661451733735',
    projectId: 'bukuing-application',
    storageBucket: 'bukuing-application.appspot.com',
    androidClientId: '661451733735-fj9jkqgelg7vnhjhfr08aigs43m7jun2.apps.googleusercontent.com',
    iosClientId: '661451733735-iqdrgfdtp81t2trn2517qai5bl6p00sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bukuing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVb2q4f7Jv6kXKfZdfWC_XfxS6DbzbIj8',
    appId: '1:661451733735:ios:c029010c67e151eb690042',
    messagingSenderId: '661451733735',
    projectId: 'bukuing-application',
    storageBucket: 'bukuing-application.appspot.com',
    androidClientId: '661451733735-fj9jkqgelg7vnhjhfr08aigs43m7jun2.apps.googleusercontent.com',
    iosClientId: '661451733735-iqdrgfdtp81t2trn2517qai5bl6p00sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bukuing',
  );
}
